image:
  name: docker/compose:1.29.1
  entrypoint: [""]

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - export IMAGE=$CI_REGISTRY/leptitcoinsante/$CI_PROJECT_NAME
  - export WEB_IMAGE=$IMAGE:bot
  - apk add --no-cache openssh-client bash
  - chmod +x ./setup_env.sh
  - bash ./setup_env.sh
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY  

build:
  stage: build
  script:
    - docker pull $IMAGE:bot || true
    - docker build . -t bot-twitter
    - docker push $IMAGE:bot

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$PRIVATE_KEY" | tr -d '\r' > ~/.ssh/authorized_keys
    - cat ~/.ssh/authorized_keys
    - chmod 700 ~/.ssh/authorized_keys
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/authorized_keys
    - ssh-keyscan -H 'gitlab.com' >> ~/.ssh/known_hosts
    - chmod +x ./deploy.sh
    - scp -o StrictHostKeyChecking=no -r ./.env ./deploy.sh ubuntu@$AWS_IP_ADDRESS:/home/ubuntu/bot
    - bash ./deploy.sh
  only:
    - master
    #./resiapi/static ./docker-compose-prod.yml 

